apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: ${{ values.description }}
  tags:
    - python
    - fastapi
    - kubernetes
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.serviceName }}
spec:
  type: service
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  system: cloudcart-platform
  dependsOn:
    - resource:default/cloudcart-postgres
