apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: CloudCart Platform Engineering Portal
  description: This Backstage instance -- the developer portal for the CloudCart platform.
  annotations:
    github.com/project-slug: ravisinghrajput95/platform-engineering-idp
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: platform-team
  lifecycle: production
