apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: backstage
  annotations:
    iam.gke.io/gcp-service-account: backstage-sql-client@project-0c628a24-2e5e-4878-861.iam.gserviceaccount.com
