apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
    backstage.io/kubernetes-id: backstage
spec:
  type: LoadBalancer
  loadBalancerIP: 34.55.255.110
  selector:
    app: backstage
  ports:
    - name: https
      port: 443
      targetPort: 7007
